# Generated by Django 5.2.17 on 2026-09-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
