# Generated by Django 5.2.17 on 2026-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_rename_phone_number_usermodel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
